langchain4j:
  ollama:
    streaming-language-model:
      base-url: http://localhost:11434
      model-name: deepseek-r1:latest
    language-model:
      base-url: http://localhost:11434
      model-name: deepseek-r1:latest
    chat-model:
      base-url: http://localhost:11434
      model-name: deepseek-r1:latest
      timeout: 60
    embedding-model:
      base-url: http://localhost:11434
      model-name: deepseek-r1:latest
    streaming-chat-model:
      base-url: http://localhost:11434
      model-name: deepseek-r1:latest